name: Testim E2E
on: [push]

jobs:
    run-testimio-cli:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                node-version: '18.18.1'
            - run: npm install -g @testim/testim-cli
            - run: testim --token "AbWAEBLQYf0JfuoCnH13NzRjBWEIdCIgZNEWsZHme2EMMfgpPL" --project "QHUZxeYKHQRxTLmLWJu4" --grid "Testim-Grid" --mode "extension" --branch "master" --test-config "FHD 1920x1080" --parallel 1 --retries 1 --timeout 120000
